name: l10nization_cli
description: A Command-Line Interface to find unused l10n translations from an arb file.
version: 2.1.0
homepage: https://github.com/lsaudon/l10nization_cli
repository: https://github.com/lsaudon/l10nization_cli
issue_tracker: https://github.com/lsaudon/l10nization_cli/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^5.12.0
  args: ^2.4.1
  cli_completion: ^0.3.0
  file: ^6.1.4
  glob: ^2.1.1
  mason_logger: ^0.2.5
  path: ^1.8.3
  pub_updater: ^0.3.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.4
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^0.3.0
  test: ^1.24.2

executables:
  l10nization:
