name: l10nization_cli
description: A Very Good Project created by Very Good CLI.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  analyzer: ^5.4.0
  args: ^2.3.2
  cli_completion: ^0.2.0
  file: ^6.1.4
  glob: ^2.1.1
  mason_logger: ^0.2.4
  path: ^1.8.3
  pub_updater: ^0.2.4
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.3.3 # 2.4.0 need dart sdk > 3.0.0
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^0.3.0
  test: ^1.23.1

executables:
  l10nization_cli:
